---
- hosts: all
  tasks:
    - name: hostname
      shell: hostname
      register: result2
    - debug: var=result2

    - name: This command will change the working directory to /work_naga
      shell: /work_naga/test.sh
      args:
        chdir: /work_naga/
    - name: pwd
      shell: pwd
      register: result1
    - debug: var=result1
