---
- hosts: all
  tasks:
    - name: hostname
      shell: hostname
      register: result1
    - debug: var=result1

    - debug:
        msg: "{{ var1 }}"

    - name: shell
      shell: "/work_naga/test.sh {{ var1 }}"
      register: result2
    - debug: var=result1

    - name: cat
      command: cat /work_naga/test.log
      register: result3
    - debug: var=result3
